name: Run remote ssh commands

on: [push]

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ secrets.HOST }}

jobs:

  build:
    name: Deploy to prod server (run ssh commands)
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to prod"
        run: sshpass -p env.PASSWORD ssh env.USERNAME@env.HOST 'cd /opt/jraychev-portfolio/src && git graph' 