name: Run remote ssh commands

on: [push]

jobs:

  build:
    name: Deploy to prod server (run ssh commands)
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to prod"
        run: sshpass -p env.PASSWORD ssh env.USER_DOMAIN 'cd /opt/jraychev-portfolio/src && git graph' 