name: Run remote ssh commands

on: [push]

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ secrets.HOST }}
  BASE_DIR: '/opt/jraychev-portfolio/src'

jobs:

  build:
    name: Deploy to prod server (run ssh commands)
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to prod"
        run: sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$HOST 'cd $BASE_DIR && git pull' 