name: Deploy

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ secrets.HOST }}
  PULL_CMD: 'cd /opt/jraychev-portfolio/src && git pull'

jobs:
  build:
    name: Deploy to prod server (run ssh commands)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Deploy to prod"
        run: sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$HOST $PULL_CMD