on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run tests within Docker container
    steps:
      - name: Rung tests
        id: tests
        uses: jpraychev/jraychev-portfolio@master